repository_type: pipeline

nf_core_version: 3.3.2

lint:
  actions_schema_validation: false
  files_exist: false
  nextflow_config: false
  nf_test_content: false
  rocrate_readme_sync: false
  actions_ci: false
  files_unchanged:
    - .github/workflows/linting.yml
    - .github/workflows/linting_comment.yml
    - .prettierrc.yml
    - CODE_OF_CONDUCT.md
    - assets/nf-core-proteomegenerator3_logo_light.png
    - docs/images/nf-core-proteomegenerator3_logo_light.png
    - docs/images/nf-core-proteomegenerator3_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  multiqc_config:
    - report_comment

template:
  org: kentsislab
  name: proteomegenerator3
  description: run Bambu for ONT transcript assembly
  author: Asher Preska Steinberg
  version: 1.0.0
  force: true
  outdir: .
  is_nfcore: false
